### ISSUE TITLE
Question: Robust and reliable: sv-tests results 

### ISSUE THREAD

**Issue by kaddkaka** [gmlarumbe/tree-sitter-systemverilog#6]
Is this parser part of the table in the linked page https://chipsalliance.github.io/sv-tests-results/ ?

Which column is it?

**Comment by gmlarumbe** [comment]
Hi @kaddkaka ,

Yes, it is the `tree_sitter_systemverilog` column.

Currently 1202 out of 1451 tests are passing. Most of the failing ones belong to the  `Keywords: 5.6.2` section (2/248 tests passing). This is a limitation of `tree-sitter` since there is no simple way to disallow hard keywords as identifiers.
